- ALPHA: 0.9
  CONSTRAINED: true
  DC_THRESHOLD: 0.075
  FEE: 0.001
  GAMMA: 0.8
- - BALANCE_USE: 0.1
    DECAY: true
    EPSILON: 0.9
    EXPLORE: true
  - BALANCE_USE: 0.1
    DECAY: true
    EPSILON: 0.7
    EXPLORE: true
  - BALANCE_USE: 0.1
    DECAY: true
    EPSILON: 0.3
    EXPLORE: true
  - BALANCE_USE: 0.1
    DECAY: false
    EPSILON: 0.1
    EXPLORE: true
  - BALANCE_USE: 0.1
    DECAY: false
    EPSILON: 0.05
    EXPLORE: true
  - BALANCE_USE: 0.1
    DECAY: false
    EPSILON: 0.025
    EXPLORE: true
- BALANCE_USE: 1
  DECAY: false
  EPSILON: -1
  EXPLORE: false
  FEE: 0.001
- AXES_LABEL_FONT_SIZE: 14
  FIGURE_TITLE_FONT_SIZE: 18
  LEGEND_FONT_SIZE: 14
  LINE_WIDTH: 2
  SUBPLOT_TITLE_FONT_SIZE: 16
  TICK_LABEL_FONT_SIZE: 12
  TITLE_Y: 1.03
- TESTING_END_DATE: 2021-12-31
  TESTING_START_DATE: 2020-01-01
  TRAINING_END_DATE: 2019-12-31 23:00:00
  TRAINING_START_DATE: 2016-01-01